# Site settings
title: Lance
SEOTitle: lance-lh
header-img: img/code.jpg
#email: xxx@gmail.com
description: "Stay hungry,Stay foolish"
#keyword: "xxxx"
url: "http://lance-lh.github.io"         
#baseurl: ""     
github_repo: "https://github.com/lance-lh/lance-lh.github.io.git"
# Sidebar settings
sidebar: true                          
sidebar-about-description: "Be a better me!"
sidebar-avatar: /img/avatar.png       

# SNS settings
RSS: false

github_username:    lance-lh

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                         

# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Featured Tags
featured-tags: true                     # use main page label
featured-condition-size: 1              # appear in main page if ...


leancloud:
  enable: true
  app_id: JSrDARlzAk8MmozvqwNbsm0f-gzGzoHsz
  app_key: Byfqq6nUuPXkLj4dOCUwszxu